vich_uploader:
    db_driver: orm

    mappings:
      forums:
           uri_prefix: /images/forum
           upload_destination: '%kernel.project_dir%/public/images/forum'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
